### ISSUE TITLE
Logged in with my Blockstack ID, says //404 user not found

### ISSUE THREAD

**Issue by thaonguyenle** [eddiejibson/chae#1]
Hi, 

I went to this website: https://chae.sh/

clicked on: "Login with Blockstack", It took me to this address: http://localhost:8888/auth?authRequest=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJqdGkiOiJjM2ZlMDUxZC04NWM3LTQ5ZmQtOGUwMS05OTdhOTEwNGE2OTMiLCJpYXQiOjE1NDc3Mzg4NDAsImV4cCI6MTU0Nzc0MjQ0MCwiaXNzIjoiZGlkOmJ0Yy1hZGRyOjFLMVhHSjZiaXVHUkFMNnlnb2phY1ZERW9ubXdHS3hSZ1YiLCJwdWJsaWNfa2V5cyI6WyIwMzkzMjY4MzRlYzZhNzU2MDllZGVhZTQ0YTFjYTliNmNjM2VkZmMyMmFkZWM1OWM1OWJhYTM4OWIyMTRhNjNhOGIiXSwiZG9tYWluX25hbWUiOiJodHRwczovL2NoYWUuc2giLCJtYW5pZmVzdF91cmkiOiJodHRwczovL2NoYWUuc2gvbWFuaWZlc3QuanNvbiIsInJlZGlyZWN0X3VyaSI6Imh0dHBzOi8vY2hhZS5zaC9sb2dpbiIsInZlcnNpb24iOiIxLjMuMSIsImRvX25vdF9pbmNsdWRlX3Byb2ZpbGUiOnRydWUsInN1cHBvcnRzX2h1Yl91cmwiOnRydWUsInNjb3BlcyI6WyJzdG9yZV93cml0ZSIsInB1Ymxpc2hfZGF0YSJdfQ.yhlSrzFolM__ApJHMcWC3Rj4CclY9u0L4_YMe8-BeavsjtaPiSbOIVPSik8UgtJkrJzQ9huRdOh5CbzFuuMlEg#coreAPIPassword=off&logServerPort=off&regtest=off

I clicked on my id: thaonguyenle.id and I see this error screen:

<img width="1031" alt="screen shot 2019-01-17 at 10 28 17 am" src="https://user-images.githubusercontent.com/39015059/51329303-3a044480-1a43-11e9-99a6-4f35175a8b7f.png">

**Comment by eddiejibson** [comment]
Hi, I'm looking into this right now and I'll let you know when I've found and patched a valid fix.

Sorry about that.

**Comment by eddiejibson** [comment]
@thaonguyenle There seems to be an issue because your Blockstack profile is lacking account information. If I view your raw profile data via [this URL](https://gaia.blockstack.org/hub/1PWzCWHcZKmGUmEWBiZX9cUMAV9YiL3cYm/profile.json), the object does not contain anything to do with your profile - a sub `account` object is missing. So, as the page you 
are visiting extracts data from here and it is not present, this error message has made itself present.

It is not an issue with names prefixing the `.id` in general because I checked this by viewing https://chae.sh/ryan.id and everything loaded fine.

**Comment by eddiejibson** [comment]
Do you have any idea(s) as to why this could have happened?

**Comment by eddiejibson** [comment]
Hi, 

No patch on my end, I'm assuming you did something - your profile is now visible: https://chae.sh/thaonguyenle.id

I see the profile picture looks stretched, though. I'll fix that.

Thanks 👍

**Comment by eddiejibson** [comment]
That's great. I'm happy to hear that it's working on your end, too.

I was wondering that too... As I said perhaps other apps were just using Gaia for storage and that's it - no profiles?
