### ISSUE TITLE
Suggestions: Browse user function

### ISSUE THREAD

**Issue by moxiegirl** [eddiejibson/chae#5]
I thought this was more of a blogger site where I could browse and find some bloggers.

**Comment by eddiejibson** [comment]
Hi again @moxiegirl,

Unfortunately due to the limitations that come with Blockstack (the tool used for decentralized authorization in this project), I can't search for user's posts. However, I am currently building another similar app with various other technologies that will allow visitors to do so.

Thanks for the suggestion 👍
